import * as THREE from './vendor/three.module.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z), clone=x=>JSON.parse(JSON.stringify(x));
const storageKey='fisher-pose-comfy-v1';const embedded=new URLSearchParams(location.search).has('embedded');let outputWidth=768,outputHeight=1024;let promptProvider=null;
const base={head:[0,1.79,0],neck:[0,1.55,0],ls:[.25,1.48,0],le:[.39,1.17,.03],lw:[.43,.87,.1],rs:[-.25,1.48,0],re:[-.39,1.17,.03],rw:[-.43,.87,.1],hip:[0,.95,0],lh:[.14,.94,0],lk:[.18,.51,.025],la:[.19,.08,.02],rh:[-.14,.94,0],rk:[-.18,.51,.025],ra:[-.19,.08,.02]};
const presets=[{id:'stand',name:'自然站立',points:base},{id:'wave',name:'抬手招呼',points:{...base,re:[-.48,1.62,0],rw:[-.44,1.94,.04],lw:[.41,1.04,.21]}},{id:'stride',name:'迈步向前',points:{...base,le:[.35,1.23,-.18],lw:[.32,.99,-.27],re:[-.32,1.21,.23],rw:[-.27,1.04,.5],lk:[.16,.56,.31],la:[.16,.18,.52],rk:[-.15,.5,-.17],ra:[-.15,.08,-.35]}},{id:'hero',name:'叉腰站姿',points:{...base,le:[.48,1.22,.02],lw:[.19,1.03,.1],re:[-.48,1.22,.02],rw:[-.19,1.03,.1],lk:[.24,.53,.02],la:[.33,.1,.04],rk:[-.22,.53,.02],ra:[-.3,.1,.04]}}];
let state={points:clone(base),azimuth:330,elevation:9,distance:3.7,bodyAngle:0,ratio:'3:4',preset:'stand',mode:'model'},shots=[],history=[],future=[],selected=null;
try{const saved=embedded?null:JSON.parse(localStorage.getItem(storageKey)||'null');if(saved&&saved.state&&Object.keys(base).every(k=>Array.isArray(saved.state.points?.[k])&&saved.state.points[k].length===3&&saved.state.points[k].every(Number.isFinite))){state={...state,...saved.state};shots=Array.isArray(saved.shots)?saved.shots.slice(0,12):[];}}catch{}
function persist(){if(embedded){$('#save-status').textContent='有修改 · 点击应用到节点';return;}try{localStorage.setItem(storageKey,JSON.stringify({state,shots}));$('#save-status').textContent='已自动保存';}catch{$('#save-status').textContent='存储已满，请导出场景';}}
function checkpoint(){history.push(clone(state));if(history.length>60)history.shift();future=[];updateHistory();}
function updateHistory(){$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;}
function undo(){if(!history.length)return;future.push(clone(state));state=history.pop();refresh();toast('已撤销');}
function redo(){if(!future.length)return;history.push(clone(state));state=future.pop();refresh();toast('已重做');}
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2100);}
const container=$('#viewport'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(37,1,.05,100);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xeff2f6,0);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;container.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','三维人物编辑视窗');renderer.domElement.tabIndex=0;
scene.add(new THREE.HemisphereLight(0xf5f8ff,0xa6afc0,2.5));const key=new THREE.DirectionalLight(0xffffff,3.5);key.position.set(3,6,4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-3;key.shadow.camera.right=3;key.shadow.camera.top=3;key.shadow.camera.bottom=-3;key.shadow.bias=-.0003;scene.add(key);const fill=new THREE.DirectionalLight(0xb7ceff,1.8);fill.position.set(-3,3,-2);scene.add(fill);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({color:0x677a97,opacity:.13}));floor.rotation.x=-Math.PI/2;floor.position.y=-.015;floor.receiveShadow=true;scene.add(floor);
const grid=new THREE.GridHelper(20,80,0xc5cedd,0xdce2eb);grid.material.transparent=true;grid.material.opacity=.58;scene.add(grid);
const ring=new THREE.Mesh(new THREE.RingGeometry(.62,.627,100),new THREE.MeshBasicMaterial({color:0xb1bfd3,transparent:true,opacity:.7,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.004;scene.add(ring);
const human=new THREE.Group();scene.add(human);const skin=new THREE.MeshStandardMaterial({color:0xcbd5e4,roughness:.38,metalness:.14});const torsoMat=new THREE.MeshStandardMaterial({color:0xd4dce8,roughness:.4,metalness:.1});const jointMat=new THREE.MeshStandardMaterial({color:0x9cacc2,roughness:.55});const blue=new THREE.MeshStandardMaterial({color:0x557ee0,roughness:.35});const coral=new THREE.MeshStandardMaterial({color:0xdf8891,roughness:.35});
const spheres={},bones=[],surfaces=[],handles=[];const connections=[['neck','ls'],['ls','le'],['le','lw'],['neck','rs'],['rs','re'],['re','rw'],['neck','hip'],['hip','lh'],['lh','lk'],['lk','la'],['hip','rh'],['rh','rk'],['rk','ra'],['neck','head']];
function mesh(geometry,material){const m=new THREE.Mesh(geometry,material);m.castShadow=true;human.add(m);return m;}
for(const [a,b]of connections){const side=b.startsWith('l')?blue:b.startsWith('r')?coral:jointMat;const isLeg=['lk','la','rk','ra'].includes(b);const outer=mesh(new THREE.CylinderGeometry(isLeg?.064:.047,isLeg?.084:.064,1,18),skin);const inner=mesh(new THREE.CylinderGeometry(.012,.012,1,10),side);bones.push({a,b,outer,inner});surfaces.push(outer);}
const jointNames={lw:'左手腕',rw:'右手腕',la:'左脚踝',ra:'右脚踝',le:'左手肘',re:'右手肘',lk:'左膝盖',rk:'右膝盖'};
for(const name of Object.keys(base)){if(name==='head')continue;const handle=name in jointNames;const side=name.startsWith('l')?blue:name.startsWith('r')?coral:jointMat;const ball=mesh(new THREE.SphereGeometry(handle?.045:.052,20,14),handle?side:jointMat);ball.userData.joint=name;spheres[name]=ball;if(handle)handles.push(ball);}
const chest=mesh(new THREE.SphereGeometry(1,36,28),torsoMat);chest.scale.set(.245,.29,.13);surfaces.push(chest);const pelvis=mesh(new THREE.SphereGeometry(1,28,20),skin);pelvis.scale.set(.18,.135,.125);surfaces.push(pelvis);const head=mesh(new THREE.SphereGeometry(1,36,28),torsoMat);head.scale.set(.115,.155,.115);surfaces.push(head);const nose=mesh(new THREE.SphereGeometry(1,14,10),skin);nose.scale.set(.028,.032,.048);surfaces.push(nose);const face=new THREE.Group();human.add(face);for(const x of [-.04,.04]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.009,10,8),new THREE.MeshBasicMaterial({color:0x7588a4}));eye.position.set(x,.018,.106);face.add(eye);}
const feet={};for(const k of ['la','ra']){feet[k]=mesh(new THREE.SphereGeometry(1,20,16),skin);feet[k].scale.set(.067,.055,.13);surfaces.push(feet[k]);}
const focusRing=mesh(new THREE.SphereGeometry(.07,18,12),new THREE.MeshBasicMaterial({color:0x456bea,wireframe:true,transparent:true,opacity:.5}));focusRing.visible=false;
const chains=[['ls','le','lw'],['rs','re','rw'],['lh','lk','la'],['rh','rk','ra']];const lengths=chains.map(([a,b,c])=>[V(...base[a]).distanceTo(V(...base[b])),V(...base[b]).distanceTo(V(...base[c]))]);
function solveIK(chain,target,bendHint){const [a,b,c]=chains[chain],root=V(...state.points[a]),oldMiddle=V(...state.points[b]),[l1,l2]=lengths[chain];const delta=target.clone().sub(root);const d=THREE.MathUtils.clamp(delta.length(),Math.abs(l1-l2)+.008,l1+l2-.001);const dir=delta.length()<.0001?V(0,-1,0):delta.normalize();const end=root.clone().addScaledVector(dir,d);const along=(l1*l1-l2*l2+d*d)/(2*d);let bend=(bendHint||oldMiddle).clone().sub(root);bend.addScaledVector(dir,-bend.dot(dir));if(bend.length()<.001){bend=V(0,0,1);bend.addScaledVector(dir,-bend.dot(dir));if(bend.length()<.001)bend=V(1,0,0).cross(dir);}bend.normalize();const middle=root.clone().addScaledVector(dir,along).addScaledVector(bend,Math.sqrt(Math.max(0,l1*l1-along*along)));state.points[b]=middle.toArray();state.points[c]=end.toArray();}
function normalizeLimbs(){chains.forEach((chain,i)=>solveIK(i,V(...state.points[chain[2]])));}
function updateHuman(){human.rotation.y=THREE.MathUtils.degToRad(state.bodyAngle);for(const [name,m]of Object.entries(spheres)){m.position.set(...state.points[name]);m.scale.setScalar(name===selected?1.35:1);}for(const b of bones){const start=V(...state.points[b.a]),end=V(...state.points[b.b]),diff=end.clone().sub(start);for(const m of [b.outer,b.inner]){m.position.copy(start).lerp(end,.5);m.scale.y=diff.length();m.quaternion.setFromUnitVectors(V(0,1,0),diff.clone().normalize());}b.inner.visible=state.mode==='skeleton';}chest.position.copy(V(...state.points.neck)).lerp(V(...state.points.hip),.43);pelvis.position.set(...state.points.hip);head.position.set(...state.points.head);nose.position.copy(head.position).add(V(0,-.005,.11));face.position.copy(head.position);face.visible=state.mode==='model';for(const name of ['la','ra'])feet[name].position.copy(V(...state.points[name])).add(V(0,-.025,.062));surfaces.forEach(m=>m.visible=state.mode==='model');focusRing.visible=!!selected;if(selected)focusRing.position.set(...state.points[selected]);human.updateMatrixWorld(true);}
function updateCamera(){const a=THREE.MathUtils.degToRad(state.azimuth),e=THREE.MathUtils.degToRad(state.elevation),target=V(0,1,0);camera.position.set(state.distance*Math.sin(a)*Math.cos(e),1+state.distance*Math.sin(e),state.distance*Math.cos(a)*Math.cos(e));camera.lookAt(target);camera.updateMatrixWorld();}
let frameWidth=300,frameHeight=400;
function resize(){const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();const a=outputWidth,b=outputHeight;frameHeight=Math.min(h-104,(w-110)*b/a);frameWidth=frameHeight*a/b;$('#output-frame').style.width=frameWidth+'px';$('#output-frame').style.height=frameHeight+'px';camera.fov=THREE.MathUtils.radToDeg(2*Math.atan(Math.tan(THREE.MathUtils.degToRad(37)/2)*h/frameHeight));camera.updateProjectionMatrix();}
new ResizeObserver(resize).observe(container);
function description(){if(promptProvider)return promptProvider(clone(state));const labels=['正面','左前侧','左侧面','左后侧','背面','右后侧','右侧面','右前侧'];return `${labels[Math.round(state.azimuth/45)%8]} · ${state.elevation>25?'高机位俯拍':state.elevation< -7?'低机位仰拍':'平视机位'} · ${state.distance<3?'近景':'全身构图'}。${presets.find(p=>p.id===state.preset)?.name||'自定义动作'}，人物朝向 ${Math.round(state.bodyAngle)}°。`;}
function syncUI(){for(const k of ['azimuth','elevation','distance','bodyAngle']){$('#'+k).value=state[k];$('#'+k+'-value').textContent=k==='distance'?Number(state[k]).toFixed(1):Math.round(state[k])+'°';}$('#description').textContent=description();$('#ratio-label').textContent=state.ratio;$$('[data-ratio]').forEach(el=>el.classList.toggle('active',el.dataset.ratio===state.ratio));$$('[data-mode]').forEach(el=>el.classList.toggle('active',el.dataset.mode===state.mode));$$('[data-pose]').forEach(el=>el.classList.toggle('active',el.dataset.pose===state.preset));$$('.view-presets [data-view]').forEach(el=>{const [a,e]=el.dataset.view.split(',').map(Number);el.classList.toggle('active',Math.abs(state.azimuth-a)<2&&Math.abs(state.elevation-e)<2);});$('#selected-joint').textContent=jointNames[selected]||'未选择';updateHistory();}
function refresh(save=true){if(state.outputWidth&&state.outputHeight){outputWidth=state.outputWidth;outputHeight=state.outputHeight;window.dispatchEvent(new CustomEvent('fisher-size',{detail:{width:outputWidth,height:outputHeight}}));}updateHuman();updateCamera();syncUI();resize();if(save)persist();}
function svgPose(points){const p=k=>[38-points[k][0]*31,67-points[k][1]*30];return `<svg viewBox="0 0 76  seventy" fill="none" xmlns="http://www.w3.org/2000/svg">${connections.filter(([a,b])=>b!=='head').map(([a,b])=>`<path d="M${p(a).join(' ')} L${p(b).join(' ')}" stroke="${b.startsWith('r')?'#b1bdd2':'#899dbe'}" stroke-width="3" stroke-linecap="round"/>`).join('')}<circle cx="${p('head')[0]}" cy="${p('head')[1]}" r="4.3" fill="#8fa2c1"/></svg>`.replace(' seventy','70');}
$('#pose-presets').innerHTML=presets.map(p=>`<button class="pose-card" data-pose="${p.id}">${svgPose(p.points)}<span>${p.name}</span></button>`).join('');
$$('[data-pose]').forEach(el=>el.onclick=()=>{checkpoint();state.points=clone(presets.find(p=>p.id===el.dataset.pose).points);state.preset=el.dataset.pose;normalizeLimbs();refresh();toast('已应用'+el.textContent.trim());});
for(const k of ['azimuth','elevation','distance','bodyAngle']){let editing=false;const input=$('#'+k);input.addEventListener('input',()=>{if(!editing){checkpoint();editing=true;}state[k]=Number(input.value);refresh(false);});input.addEventListener('change',()=>{editing=false;persist();});}
$$('[data-view]').forEach(el=>el.onclick=()=>{checkpoint();[state.azimuth,state.elevation]=el.dataset.view.split(',').map(Number);refresh();});
$$('[data-mode]').forEach(el=>el.onclick=()=>{checkpoint();state.mode=el.dataset.mode;refresh();});
$$('[data-ratio]').forEach(el=>el.onclick=()=>{checkpoint();state.ratio=el.dataset.ratio;[outputWidth,outputHeight]=({'1:1':[1024,1024],'3:4':[768,1024],'16:9':[1536,864]})[state.ratio];state.outputWidth=outputWidth;state.outputHeight=outputHeight;window.dispatchEvent(new CustomEvent('fisher-size',{detail:{width:outputWidth,height:outputHeight}}));refresh();});
$$('[data-tab]').forEach(el=>el.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===el));$('#camera-panel').hidden=el.dataset.tab!=='camera';$('#pose-panel').hidden=el.dataset.tab!=='pose';});
function resetCamera(){checkpoint();Object.assign(state,{azimuth:330,elevation:9,distance:3.7});refresh();toast('已恢复初始取景');}$('#reset-camera').onclick=resetCamera;$('#center-view').onclick=resetCamera;renderer.domElement.ondblclick=resetCamera;
$('#undo').onclick=undo;$('#redo').onclick=redo;
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if(e.key==='Escape'){selected=null;refresh(false);}});
$('#reset-pose').onclick=()=>{checkpoint();state.points=clone(base);state.preset='stand';refresh();};
$('#mirror').onclick=()=>{checkpoint();const next=clone(state.points);for(const k of Object.keys(next)){const other=k.startsWith('l')?'r'+k.slice(1):k.startsWith('r')?'l'+k.slice(1):k;next[k]=[-state.points[other][0],state.points[other][1],state.points[other][2]];}state.points=next;state.preset='custom';refresh();toast('已镜像动作');};
$('#toggle-grid').onclick=()=>{const el=$('.thirds');el.hidden=!el.hidden;$('#toggle-grid').setAttribute('aria-pressed',String(!el.hidden));};
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let drag=null;
function rayFromEvent(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;rayFromEvent(e);const hit=raycaster.intersectObjects(handles)[0];checkpoint();selected=hit?.object.userData.joint||null;drag={x:e.clientX,y:e.clientY,a:state.azimuth,e:state.elevation,joint:selected,start:clone(state)};if(selected){const pos=human.localToWorld(V(...state.points[selected]));drag.plane=new THREE.Plane().setFromNormalAndCoplanarPoint(camera.getWorldDirection(V()),pos);const point=V();raycaster.ray.intersectPlane(drag.plane,point);drag.offset=pos.sub(point);$('#selection-hint').textContent='正在调整'+jointNames[selected];}renderer.domElement.setPointerCapture(e.pointerId);renderer.domElement.style.cursor='grabbing';refresh(false);});
renderer.domElement.addEventListener('pointermove',e=>{rayFromEvent(e);if(!drag){renderer.domElement.style.cursor=raycaster.intersectObjects(handles).length?'grab':'default';return;}if(drag.joint){const hit=V();if(raycaster.ray.intersectPlane(drag.plane,hit)){hit.add(drag.offset);human.worldToLocal(hit);if(['la','ra'].includes(drag.joint))hit.y=Math.max(.075,hit.y);const i=chains.findIndex(chain=>chain.includes(drag.joint));if(chains[i][2]===drag.joint)solveIK(i,hit);else solveIK(i,V(...state.points[chains[i][2]]),hit);state.preset='custom';}}else{state.azimuth=(drag.a-(e.clientX-drag.x)*.42+720)%360;state.elevation=THREE.MathUtils.clamp(drag.e+(e.clientY-drag.y)*.25,-30,75);}refresh(false);});
function endDrag(e){if(!drag)return;drag=null;if(renderer.domElement.hasPointerCapture(e.pointerId))renderer.domElement.releasePointerCapture(e.pointerId);renderer.domElement.style.cursor='default';$('#selection-hint').textContent=selected?jointNames[selected]+' · 拖动其他关节继续调整':'拖动彩色关节，调整人物动作';persist();}renderer.domElement.addEventListener('pointerup',endDrag);renderer.domElement.addEventListener('pointercancel',endDrag);renderer.domElement.addEventListener('lostpointercapture',endDrag);
let wheelTimer;renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();if(!wheelTimer)checkpoint();state.distance=THREE.MathUtils.clamp(state.distance+e.deltaY*.003,2.2,7);refresh(false);clearTimeout(wheelTimer);wheelTimer=setTimeout(()=>{wheelTimer=null;persist();},250);},{passive:false});
function render(){renderer.render(scene,camera);requestAnimationFrame(render);}normalizeLimbs();refresh(false);render();
function croppedPreview(){renderer.render(scene,camera);const source=renderer.domElement,scale=source.width/container.clientWidth,out=document.createElement('canvas');out.width=240;out.height=Math.round(240*frameHeight/frameWidth);const ctx=out.getContext('2d');ctx.fillStyle='#eff2f6';ctx.fillRect(0,0,out.width,out.height);ctx.drawImage(source,(source.width-frameWidth*scale)/2,(source.height-frameHeight*scale)/2,frameWidth*scale,frameHeight*scale,0,0,out.width,out.height);return out.toDataURL('image/jpeg',.75);}
function renderShots(){$('#shot-count').textContent=shots.length;$('#shot-strip').innerHTML='';if(!shots.length){const el=document.createElement('div');el.className='empty-shots';el.textContent='遇到喜欢的构图，就把它存下来。';$('#shot-strip').append(el);}shots.forEach((shot,i)=>{const el=document.createElement('button');el.className='shot';const image=document.createElement('img');image.src=shot.image;image.alt=shot.name;const text=document.createElement('span'),name=document.createElement('b'),sub=document.createElement('small');name.textContent=shot.name;sub.textContent=`${Math.round(shot.state.azimuth)}° / ${Math.round(shot.state.elevation)}° · ${shot.state.ratio}`;text.append(name,sub);el.append(image,text);el.title='恢复'+shot.name;el.onclick=()=>{checkpoint();state=clone(shot.state);selected=null;refresh();toast('已恢复'+shot.name);};const del=document.createElement('span');del.className='delete';del.textContent='×';del.title='删除镜头';del.setAttribute('role','button');del.tabIndex=0;const remove=e=>{e.stopPropagation();shots.splice(i,1);renderShots();persist();};del.onclick=remove;del.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();remove(e);}};el.append(del);$('#shot-strip').append(el);});}
$('#save-shot').onclick=()=>{if(shots.length>=12){toast('最多收藏 12 个镜头，请先删除一个');return;}const name='镜头 '+String(shots.length+1).padStart(2,'0');shots.push({name,state:clone(state),image:croppedPreview()});renderShots();persist();toast('已保存当前动作与机位');};renderShots();
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export-scene').onclick=()=>{download(new Blob([JSON.stringify({version:1,application:'Fisher Pose prototype',state,shots},null,2)],{type:'application/json'}),'fisher-pose-scene.json');toast('场景已导出');};
function projectJoint(name,w,h){const point=V(...state.points[name]);if(name==='head')point.add(V(0,-.005,.11));const world=human.localToWorld(point).project(camera);const stageX=(world.x+1)*container.clientWidth/2,stageY=(1-world.y)*container.clientHeight/2;return [(stageX-(container.clientWidth-frameWidth)/2)/frameWidth*w,(stageY-(container.clientHeight-frameHeight)/2)/frameHeight*h];}
$('#export-pose').onclick=()=>{const out=document.createElement('canvas');out.width=outputWidth;out.height=outputHeight;const ctx=out.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,out.width,out.height);const palette=['#ff0000','#ff5500','#ffaa00','#ffff00','#aaff00','#55ff00','#00ff00','#00ff55','#00ffaa','#00ffff','#00aaff','#0055ff','#0000ff','#5500ff','#aa00ff','#ff00ff','#ff00aa','#ff0055'];const limbs=[['neck','rs'],['neck','ls'],['rs','re'],['re','rw'],['ls','le'],['le','lw'],['neck','rh'],['rh','rk'],['rk','ra'],['neck','lh'],['lh','lk'],['lk','la'],['neck','head']];ctx.lineCap='round';limbs.forEach(([a,b],i)=>{const p=projectJoint(a,out.width,out.height),q=projectJoint(b,out.width,out.height);ctx.strokeStyle=palette[i];ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(...p);ctx.lineTo(...q);ctx.stroke();});const order=['head','neck','rs','re','rw','ls','le','lw','rh','rk','ra','lh','lk','la'];order.forEach((name,i)=>{const p=projectJoint(name,out.width,out.height);ctx.fillStyle=palette[i];ctx.beginPath();ctx.arc(...p,5,0,Math.PI*2);ctx.fill();});out.toBlob(blob=>download(blob,'fisher-pose.png'),'image/png');toast('已导出当前画框的身体骨架图');};
$('#copy-description').onclick=async()=>{try{await navigator.clipboard.writeText(description());toast('已复制镜头描述');}catch{toast('浏览器限制复制，请手动选中描述复制');}};
let referenceUrl=null;function loadReference(file){if(!file||!file.type.startsWith('image/')){toast('请选择图片文件');return;}if(file.size>20*1024*1024){toast('请选择小于 20 MB 的图片');return;}if(referenceUrl)URL.revokeObjectURL(referenceUrl);referenceUrl=URL.createObjectURL(file);$('#reference-image').src=referenceUrl;$('#reference-image').hidden=false;$('#upload-label').style.backgroundImage=`linear-gradient(#ffffffaa,#ffffffaa),url("${referenceUrl}")`;$('#clear-reference').hidden=false;$('#opacity-control').hidden=false;toast('参考图已叠加，可调整透明度');}$('#reference-file').onchange=e=>loadReference(e.target.files[0]);$('#upload-label').ondragover=e=>e.preventDefault();$('#upload-label').ondrop=e=>{e.preventDefault();loadReference(e.dataTransfer.files[0]);};$('#opacity').oninput=e=>$('#reference-image').style.opacity=Number(e.target.value)/100;$('#clear-reference').onclick=()=>{$('#reference-image').hidden=true;$('#reference-image').removeAttribute('src');$('#upload-label').style.backgroundImage='none';$('#clear-reference').hidden=true;$('#opacity-control').hidden=true;$('#reference-file').value='';if(referenceUrl)URL.revokeObjectURL(referenceUrl);referenceUrl=null;};$('#select-person').onclick=()=>toast('当前正在编辑人物 01');
// Exposes read-only diagnostics for interaction verification.
window.poseStudio={snapshot:()=>clone(state),joints:()=>Object.fromEntries(handles.map(m=>{const p=human.localToWorld(m.position.clone()).project(camera);const r=renderer.domElement.getBoundingClientRect();return [m.userData.joint,{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2}];})),boneLengths:()=>chains.map(([a,b,c])=>[V(...state.points[a]).distanceTo(V(...state.points[b])),V(...state.points[b]).distanceTo(V(...state.points[c]))])};

window.poseStudio.load=(payload)=>{const scene=JSON.parse(payload.scene_json||'{}');state={...state,...(scene.state||scene)};shots=scene.shots||[];history=[];future=[];selected=null;outputWidth=Number(payload.width);outputHeight=Number(payload.height);state.outputWidth=outputWidth;state.outputHeight=outputHeight;state.ratio=outputWidth+':'+outputHeight;refresh(false);renderShots();$('#save-status').textContent='已载入节点设置';};
window.poseStudio.serialize=()=>JSON.stringify({version:1,state,shots});
window.poseStudio.setPromptProvider=(fn)=>{promptProvider=fn;syncUI();};
window.poseStudio.setSize=(width,height)=>{outputWidth=width;outputHeight=height;state.outputWidth=width;state.outputHeight=height;state.ratio=width+':'+height;refresh(false);};
window.poseStudio.projected=()=>Object.fromEntries(Object.keys(base).map(name=>[name,projectJoint(name,outputWidth,outputHeight)]));
await import('./bridge.mjs');
