(async () => {
  const { app } = await import('/scripts/app.js');
  const sleep = ms => new Promise(r => setTimeout(r, ms));
  const assert = (value, message) => { if (!value) throw new Error(message); };
  const node = app.graph._nodes.find(n => n.type === 'FisherQwenFreePose');
  if (!document.querySelector('dialog iframe')) node.widgets.find(w => w.type === 'button').callback();
  const frame = document.querySelector('dialog iframe');
  for (let i = 0; i < 100 && !frame.contentDocument.querySelector('#loading').hidden; i++) await sleep(200);
  const fp = frame.contentWindow.freePose, d = frame.contentDocument;
  assert(!d.querySelector('#mode-camera').disabled, 'camera must be available in unified workflow');
  assert(!d.querySelector('#generate-editor').hidden, 'generate action missing');
  fp.setAutoFit(false);
  fp.setAngle({ yaw: 0, pitch: 0, zoom: 1, offsetX: 0, offsetY: 0 });
  fp.applyCommonPose(fp.galleries.common.find(p => p.spec.id === 'hands-up'));
  const first = JSON.parse(await fp.serialize());
  assert(!first.anyAngle.enabled, 'front must skip camera processing');
  fp.setEditMode('camera'); fp.setAngle({ yaw: 35, pitch: 15, zoom: 1.2 });
  const shot = JSON.parse(await fp.serialize());
  assert(shot.anyAngle.enabled && shot.anyAngle.camera.zoom === 1.2, 'camera and zoom not persisted');
  assert(shot.poseReference === first.poseReference, 'camera changed VNCCS front reference');
  fp.setEditMode('pose');
  fp.viewer.camera.position.x += 5; fp.viewer.orbit.update();
  const inspected = JSON.parse(await fp.serialize());
  assert(JSON.stringify(inspected.anyAngle.camera) === JSON.stringify(shot.anyAngle.camera), 'inspection changed the shot');
  await sleep(700);
  let captures = 0; const originalCapture = fp.viewer.capture;
  fp.viewer.capture = function(...args) { captures++; return originalCapture.apply(this, args); };
  await sleep(900); fp.viewer.capture = originalCapture;
  assert(captures === 0, 'idle camera preview loops');
  fp.setAngle({ yaw: 0, pitch: 0, zoom: 1, offsetX: 0, offsetY: 0 });
  fp.applyCommonPose(fp.galleries.common.find(p => p.spec.id === 'wave'));
  const second = JSON.parse(await fp.serialize());
  assert(first.poseReference !== second.poseReference, 'second pose captured the first pose');
  const width = node.widgets.find(w => w.name === 'width').value;
  d.querySelector('#output-width').value = 768; d.querySelector('#output-width').dispatchEvent(new Event('change'));
  assert(node.widgets.find(w => w.name === 'width').value === width, 'reference width changed final width');
  d.querySelector('#output-width').value = 1024; d.querySelector('#output-width').dispatchEvent(new Event('change'));
  return { passed: true, checks: ['camera capability', 'generate button', 'front skips camera', 'camera persistence', 'fixed VNCCS reference', 'inspection isolation', 'no idle preview loop', 'consecutive poses', 'independent sizes'] };
})()
