import assert from 'node:assert/strict';
import { detectionPrompt } from '../web/editor/pose-detector.mjs';
import { openPoseJSON } from '../web/editor/keypoint-editor.mjs';
import { readPoseKeypoints } from '../web/editor/pose-keypoints.mjs';
import { omitPoseShape, restorePoseShape } from '../web/editor/pose-shape.mjs';
import { shapeRecord, estimateProportions } from '../web/editor/body-presets.mjs';
import { resultRecords, inputTargets } from '../web/result-history.mjs';

const options = { sdpose: true, checkpoints: ['sdpose.safetensors'], dwpose: true, dwposeSchema: { input: { optional: {} } } };
const sd = detectionPrompt('sdpose', 'photo.png', options, options.checkpoints[0]);
assert.deepEqual(sd[4].inputs.source, ['2', 0]);
assert.deepEqual(sd[2].inputs.vae, ['6', 2]);
assert.deepEqual(detectionPrompt('dwpose', 'photo.png', options)[4].inputs.source, ['2', 1]);
assert.throws(() => detectionPrompt('sdpose', 'photo.png', options, 'missing'), /安装/);
const points = { head: [50.4, 10], neck: [50, 25], ls: [65, 30], le: [80, 55], lw: [92.1, 75], rs: [35, 30], re: [20, 55], rw: [8, 75], lh: [60, 85], lk: [65, 115], la: [68, 150], rh: [40, 85], rk: [35, 115], ra: [32, 150] };
const detection = { width: 100, height: 160, people: [points, { ls: [65, 30], le: [80, 55] }] };
assert.deepEqual(readPoseKeypoints(openPoseJSON(detection)), detection, 'subpixel and missing joints survive JSON export/import');
const source = { mesh: { height: .7 }, proportions: { thigh: 1.2 }, pose: { bones: { calf_l: [20, 0, 0] }, bonePositions: { calf_l: [1, 2, 3] }, ikEffectorPositions: { leftFoot: [1, 3, 4] } }, transform: { x: 3, z: 4 }, anyAngle: { yaw: 45 } };
const stripped = omitPoseShape(source);
assert.equal(stripped.mesh, undefined); assert.equal(stripped.pose.bonePositions, undefined); assert.equal(stripped.pose.ikEffectorPositions, undefined);
assert.deepEqual(stripped.pose.bones, source.pose.bones); assert.ok(source.pose.bonePositions);
const current = [{ mesh: { height: .3 }, proportions: { thigh: .8 } }, { mesh: { height: .9 }, proportions: { thigh: 1.3 } }];
const loaded = restorePoseShape({ includeShape: false, doc: { ...stripped, people: [stripped, stripped] } }, current);
assert.deepEqual(loaded.people.map(shapeRecord), current); assert.equal(loaded.anyAngle.yaw, 45);
assert.deepEqual(restorePoseShape({ doc: source }, current), source, 'legacy records include shape');
assert.deepEqual(shapeRecord(source), { mesh: source.mesh, proportions: source.proportions });
const rig = Object.fromEntries(Object.entries(points).map(([key, value]) => [key, [...value.map(x => x / 10), 0]]));
const proportions = Object.fromEntries(['shoulder', 'spine', 'upper_arm', 'forearm', 'thigh', 'shin'].map(k => [k, 1]));
const ranges = Object.fromEntries(Object.keys(proportions).map(k => [k, [.6, 1.6]]));
const fitted = estimateProportions(points, rig, proportions, ranges);
for (const value of Object.values(fitted)) assert.ok(Math.abs(value - 1) < 1e-10);
assert.throws(() => estimateProportions({ ls: [1, 1] }, rig, proportions, ranges), /至少/);
const distorted = estimateProportions({ ...points, lw: [999, 1] }, rig, proportions, ranges);
for (const value of Object.values(distorted)) assert.ok(value >= .925 && value <= 1.15);

const prompt = { 1: { class_type: 'LoadImage', inputs: { image: 'original.png' } }, 6: { class_type: 'FisherQwenFreePose', inputs: { reference_image: ['1', 0] } }, 7: { class_type: 'KSampler', inputs: { positive: ['6', 0] } }, 8: { class_type: 'VAEDecode', inputs: { samples: ['7', 0] } }, 28: { class_type: 'SaveImage', inputs: { images: ['8', 0] } }, 31: { class_type: 'PreviewImage', inputs: { images: ['8', 0] } }, 32: { class_type: 'SaveImage', inputs: { images: ['1', 0] } } };
const file = { filename: 'result.png', type: 'output', subfolder: '' };
const job = { prompt: [1, 'id', prompt], status: { status_str: 'success' }, outputs: { 28: { images: [file] }, 31: { images: [file] }, 32: { images: [file] } } };
assert.equal(resultRecords({ one: job }, 6).length, 1, 'only final dependent SaveImage, no previews or other saves');
assert.deepEqual(resultRecords({ one: job }, 6)[0].sources, ['original.png']);
assert.equal(resultRecords({ one: { ...job, status: { status_str: 'error' } } }, 6).length, 0);
const a = { id: 1, type: 'LoadImage', mode: 0 }, b = { id: 2, type: 'LoadImage', mode: 4 };
const graph = { links: { 1: { origin_id: 1 }, 2: { origin_id: 2 } }, getNodeById: id => id === 1 ? a : b };
const node = { graph, inputs: [{ name: 'reference_image', link: 1 }, { name: 'reference_image_2', link: 2 }] };
assert.deepEqual(inputTargets(node), [a]); a.mode = 4; b.mode = 0; assert.deepEqual(inputTargets(node), [b]);
a.mode = 0; assert.equal(inputTargets(node).length, 2); a.mode = b.mode = 4; assert.equal(inputTargets(node).length, 0);
console.log('pose toolkit: detector routes, raw coordinates, shape isolation, conservative fitting, final history and portrait switching passed');
