import assert from 'node:assert/strict';
import { readPoseKeypoints, requireBody, largestBody } from '../web/editor/pose-keypoints.mjs';
import { ORDER } from '../web/editor/state.mjs';
const triples = Array.from({ length: 18 }, (_, i) => [10.25 + i * 3, 20.75 + i * 5, 1]);
const frame = { canvas_width: 512, canvas_height: 768, people: [{ pose_keypoints_2d: triples.flat() }] };
const original = JSON.stringify(frame);
const detected = readPoseKeypoints(JSON.stringify([frame]));
assert.deepEqual(detected.people[0].rw, triples[4].slice(0, 2), 'fractional original coordinates survive');
assert.deepEqual(Object.keys(requireBody(detected.people[0])), ORDER);
assert.equal(JSON.stringify(frame), original, 'parsing does not mutate the detector result');
const nested = structuredClone(frame);
nested.people[0].pose_keypoints_2d = triples;
assert.deepEqual(readPoseKeypoints(nested), detected, 'nested and flat coordinates match');
const body25 = Array.from({ length: 25 }, (_, i) => [i + 1, i + 2, 1]);
assert.deepEqual(readPoseKeypoints({ ...frame, people: [{ pose_keypoints_2d: body25.flat() }] }).people[0].rh, [10, 11]);
const missing = structuredClone(frame);
missing.people[0].pose_keypoints_2d[4 * 3 + 2] = 0;
assert.throws(() => requireBody(readPoseKeypoints(missing).people[0]), /关节不完整/);
assert.throws(() => readPoseKeypoints({ ...frame, people: [] }), /未识别到/);
const invalid = structuredClone(frame);
invalid.people[0].pose_keypoints_2d[0] = NaN;
assert.throws(() => requireBody(readPoseKeypoints(invalid).people[0]), /关节不完整/);
assert.equal(largestBody([{ head: [1, 1], la: [1, 5] }, detected.people[0]]), detected.people[0]);
console.log('pose-keypoints: original coordinates, formats, missing joints and selection passed');
